### ISSUE TITLE
Open documents imported by the user automatically

### ISSUE THREAD

**Issue by pvh** [inkandswitch/vscode-hypermerge#22]
Don't make them find it in the list of documents and open it after. We should also focus it in the browser.

**Comment by mjtognetti** [comment]
Taking a stab at this. Currently hitting a race where the document opens in VS Code before the hm doc is fully loaded. Result is the document renders as `{}` in the editor and `(No /title)` in the tree viewer, and then gets stuck and doesn't load actual contents.

Other times this works fine - even if it initially renders as `{}`.

**Comment by mjtognetti** [comment]
Implemented in master (minus what looks like a race)
